# Generated by Django 4.1 on 2023-11-29 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='instrutor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primeiro_nome', models.CharField(max_length=50, verbose_name='Nome')),
                ('ultimo_nome', models.TextField(max_length=100, verbose_name='Sobrenome')),
                ('telefone', models.TextField(max_length=100, verbose_name='Telefone')),
                ('email', models.TextField(max_length=100, verbose_name='Email')),
                ('especializacao', models.TextField(max_length=100, verbose_name='Especialização')),
            ],
            options={
                'verbose_name': 'instrutor',
                'verbose_name_plural': 'instrutores',
                'ordering': ['id'],
            },
        ),
    ]
