# Generated by Django 4.1 on 2023-12-01 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='exercicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nome')),
                ('description', models.TextField(max_length=100, verbose_name='Descricao')),
                ('dificuldade', models.CharField(max_length=50, verbose_name='Dificuldade')),
                ('area_desenvolvimento', models.CharField(max_length=50, verbose_name='Área de desenvolvimento')),
            ],
            options={
                'verbose_name': 'exercicio',
                'verbose_name_plural': 'exercicios',
                'ordering': ['id'],
            },
        ),
    ]
