# Generated by Django 4.1 on 2023-11-28 22:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('avaliacao', '0001_initial'),
        ('plano', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primeiro_nome', models.CharField(max_length=50, verbose_name='Nome')),
                ('ultimo_nome', models.CharField(max_length=100, verbose_name='Sobrenome')),
                ('endereço', models.CharField(max_length=200, verbose_name='Endereco')),
                ('telefone', models.CharField(max_length=20, verbose_name='Telefone celular')),
                ('email', models.EmailField(max_length=254, verbose_name='E-mail')),
                ('genero', models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino'), ('O', 'Outro')], max_length=1, verbose_name='Genero')),
            ],
            options={
                'verbose_name': 'cliente',
                'verbose_name_plural': 'cliente',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='clienteplano',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cliente.cliente')),
                ('plano', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plano.plano')),
            ],
            options={
                'verbose_name': 'plano',
                'verbose_name_plural': 'planos',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='clienteavaliacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avaliacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='avaliacao.avaliacao')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cliente.cliente')),
            ],
            options={
                'verbose_name': 'avaliacao fisica',
                'verbose_name_plural': 'avaliacoes fisicas',
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='cliente',
            name='cliente_avaliacao',
            field=models.ManyToManyField(blank=True, through='cliente.clienteavaliacao', to='avaliacao.avaliacao'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='cliente_plano',
            field=models.ManyToManyField(blank=True, through='cliente.clienteplano', to='plano.plano'),
        ),
    ]
