# Generated by Django 4.1 on 2023-11-30 05:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('plano', '0001_initial'),
        ('nivel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primeiro_nome', models.CharField(max_length=50, verbose_name='Nome')),
                ('ultimo_nome', models.CharField(max_length=100, verbose_name='Sobrenome')),
                ('endereço', models.CharField(max_length=200, verbose_name='Endereco')),
                ('telefone', models.CharField(max_length=20, verbose_name='Telefone celular')),
                ('email', models.EmailField(max_length=254, verbose_name='E-mail')),
                ('genero', models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino'), ('O', 'Outro')], max_length=1, verbose_name='Genero')),
                ('cliente_nivel', models.ManyToManyField(to='nivel.nivel')),
                ('cliente_plano', models.ManyToManyField(to='plano.plano')),
            ],
            options={
                'verbose_name': 'cliente',
                'verbose_name_plural': 'clientes',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='clienteplano',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cliente.cliente')),
                ('plano', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plano.plano')),
            ],
            options={
                'verbose_name': 'plano',
                'verbose_name_plural': 'planos',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='clientenivel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cliente.cliente')),
                ('nivel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nivel.nivel')),
            ],
            options={
                'verbose_name': 'nivel',
                'verbose_name_plural': 'niveis',
                'ordering': ['id'],
            },
        ),
    ]
