# Generated by Django 4.1 on 2023-11-30 00:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cliente', '0002_alter_cliente_options'),
        ('instrutor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='agendamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.CharField(max_length=50, verbose_name='Data')),
                ('hora', models.CharField(max_length=100, verbose_name='Horário')),
                ('local', models.CharField(max_length=200, verbose_name='Endereco')),
                ('agendamento_cliente', models.ManyToManyField(to='cliente.cliente')),
                ('agendamento_instrutor', models.ManyToManyField(to='instrutor.instrutor')),
            ],
            options={
                'verbose_name': 'agendamento',
                'verbose_name_plural': 'agendamentos',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='agendamentoinstrutor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agendamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agendamento.agendamento')),
                ('instrutor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instrutor.instrutor')),
            ],
            options={
                'verbose_name': 'Instrutor',
                'verbose_name_plural': 'Instrutores',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='agendamentocliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agendamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agendamento.agendamento')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cliente.cliente')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['id'],
            },
        ),
    ]
