# Generated by Django 4.1 on 2023-11-30 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='nivel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel', models.TextField(max_length=50, verbose_name='nivel')),
            ],
            options={
                'verbose_name': 'nivel',
                'verbose_name_plural': 'nivel',
                'ordering': ['id'],
            },
        ),
    ]
